### ISSUE TITLE
syntax highlighting for .hcl files

### ISSUE THREAD

**Issue by jmyers82** [hashicorp/vscode-sentinel#8]
It looks like we are getting some highlighting for the .sentinel files but nothing for the hcl files? Could this be an enhancement?

.sentinel files
![image](https://user-images.githubusercontent.com/25810385/156814706-11b34a3c-98db-4082-b61b-49053548e408.png)

.hcl files
![image](https://user-images.githubusercontent.com/25810385/156814766-aa35954b-e993-474c-a10d-300151ab1c8a.png)

**Comment by jmyers82** [comment]
Well ... actually with very little looking.. I found an HCL extension.  so I will close this.

**Comment by jpogran** [comment]
Hi @jmyers82, this is on our radar: https://github.com/hashicorp/vscode-terraform/issues/639. The ticket looks like it's stale but we're actively working on this space. Watch this repo for updates :)

**Comment by glennsarti** [comment]
Thanks @jmyers82  ... and yes a 👍 to @jpogran .  We're working on something
